site_name: CodiumAI Release Notes Digest
site_description: Latest release notes of Codiumate and PR-Agent

nav: 
  - Home: 'index.md'
  - JetBrains: 'versions/latest/jetbrains.md'
  - VSCode: 'versions/latest/vscode.md'
  - PR-Agent: 'versions/latest/pr-agent.md'
  - Older Versions: 
    - April 4, 2024:
      - 'versions/2024-04-04/index.md'
      - JetBrains: 'versions/2024-04-04/jetbrains.md'
      - VSCode: 'versions/2024-04-04/vscode.md'
    - March 28, 2024:
      - 'versions/2024-03-28/index.md'
      - JetBrains: 'versions/2024-03-28/jetbrains.md'
      - VSCode: 'versions/2024-03-28/vscode.md'
      - PR-Agent: 'versions/2024-03-28/pr-agent.md'

theme:
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  name: material
  font: false
  features:
    - navigation.indexes
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  language: en
  custom_dir: overrides
    
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: custom
      accent: custom 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: custom
      accent: custom
    
    

plugins:
  - social
  - search
  - glightbox
  - mkdocs-video:
      css_style:
        position: relative;
        width: "70%"
        height: "35.172vw"
        margin-left: "auto"
        margin-right: "auto"
        display: "block"

extra:
  generator: false
  analytics:
    provider: custom
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Codium-ai
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/SgSxuQ65GF
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Codium-AI
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/codiumai
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CodiumAI
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/codiumai/

extra_css:
  - css/custom.css

markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      title: On this page
      toc_depth: 1
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


copyright: |
  &copy; 2024 <a href="https://www.codium.ai/"  target="_blank" rel="noopener">CodiumAI</a>