site_name: Qodo Release Notes Digest
site_description: Latest release notes of Qodo Gen and Qodo Merge

nav: 
  - Qodo Release Notes: 'index.md'
  - qodoGen: 'versions/latest/qodo-gen.md'
  - qodoMerge: 'versions/latest/qodo-merge.md'
  - Older Versions: 
    - August 26, 2024:
      - 'versions/2024-08-26/index.md'
      - JetBrains: 'versions/2024-08-26/jetbrains.md'
      - VSCode: 'versions/2024-08-26/vscode.md'
      - PR-Agent: 'versions/2024-08-26/pr-agent.md'
    - July 23, 2024:
      - JetBrains: 'versions/2024-07-23/jetbrains.md'
      - VSCode: 'versions/2024-07-23/vscode.md'
      - PR-Agent: 'versions/2024-07-23/pr-agent.md'
    - May 30, 2024:
      - JetBrains: 'versions/2024-05-30/jetbrains.md'
      - VSCode: 'versions/2024-05-30/vscode.md'
      - PR-Agent: 'versions/2024-05-30/pr-agent.md'

theme:
  logo: assets/logo-mark.svg
  favicon: assets/favicon.ico
  name: material
  font: false
  features:
    - navigation.indexes
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  language: en
  custom_dir: overrides
    
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: custom
      accent: custom 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: custom
      accent: custom
    
    

plugins:
  - social
  - search
  - glightbox
  - mkdocs-video:
      css_style:
        position: relative;
        width: "40%"
        height: "22.172vw"
        margin-left: "20px"
        margin-right: "20px"
        display: "block"

extra:
  generator: false
  analytics:
    provider: custom
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Codium-ai
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/SgSxuQ65GF
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@QodoAI
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/qodoai
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/QodoAI
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/qodo_ai

extra_css:
  - css/custom.css

markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      title: On this page
      toc_depth: 1
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


copyright: |
  &copy; 2024 <a href="https://www.qodo.ai/"  target="_blank" rel="noopener">Qodo</a>